CREATE TABLE pitchers (unique_id VARCHAR(20), 
                       player_id INTEGER,
                       pitch CHAR(2),
                       mph REAL,
                       ev_mph REAL,
                       pitcher_name VARCHAR(255),
                       batter_name VARCHAR(255),
                       dist INTEGER,
                       spin_rate INTEGER,
                       launch_angle REAL,
                       per_vel REAL,
                       zone INTEGER,
                       game_date DATE,
                       ab_count CHAR(3),
                       inning VARCHAR(10),
                       pitch_result VARCHAR(255),
                       ab_result VARCHAR(255),
                       PRIMARY KEY (unique_id));
                       
CREATE TABLE pitcher_ids (unique_id VARCHAR(20),
                          player_id INTEGER,
                          player_name VARCHAR(255),
                          total_pitches INTEGER,
                          ba REAL,
                          iso REAL,
                          babip REAL,
                          slg REAL,
                          woba REAL,
                          xwoba REAL,
                          xba REAL,
                          hits INTEGER,
                          abs INTEGER,
                          launch_speed REAL,
                          launch_angle REAL,
                          spin_rate INTEGER,
                          velocity REAL,
                          effective_speed REAL,
                          whiffs INTEGER,
                          swings INTEGER,
                          takes INTEGER,
                          eff_min_vel REAL,
                          release_extension REAL,
                          pos3_int_start_distance INTEGER,
                          pos4_int_start_distance INTEGER,
                          pos5_int_start_distance INTEGER,
                          pos6_int_start_distance INTEGER,
                          pos7_int_start_distance INTEGER,
                          pos8_int_start_distance INTEGER,
                          pos9_int_start_distance INTEGER,
                          PRIMARY KEY (unique_id));
                          
CREATE TABLE batter_ids (unique_id VARCHAR(20), 
                         player_id INTEGER,
                         player_name VARCHAR(255),
                         total_pitches INTEGER,
                         ba REAL,
                         iso REAL,
                         babip REAL,
                         slg REAL,
                         woba REAL,
                         xwoba REAL,
                         xba REAL,
                         hits INTEGER,
                         abs INTEGER,
                         launch_speed REAL,
                         launch_angle REAL,
                         spin_rate INTEGER,
                         velocity REAL,
                         effective_speed REAL,
                         whiffs INTEGER,
                         swings INTEGER,
                         takes INTEGER,
                         eff_min_vel REAL,
                         release_extension REAL,
                         pos3_int_start_distance INTEGER,
                         pos4_int_start_distance INTEGER,
                         pos5_int_start_distance INTEGER,
                         pos6_int_start_distance INTEGER,
                         pos7_int_start_distance INTEGER,
                         pos8_int_start_distance INTEGER,
                         pos9_int_start_distance INTEGER,
                         PRIMARY KEY (unique_id));